channels:
  - conda-forge
  - aihabitat
dependencies:
  - withbullet
  - habitat-sim-ovmm-challenge-2023
  - pip:
    - gym>=0.22.0,<0.23.1
    - yacs>=0.1.8
    - numpy-quaternion>=2019.3.18.14.33.20
    - attrs>=19.1.0
