channels:
  - conda-forge
  - aihabitat
dependencies:
  - habitat-sim==0.2.4
  - withbullet
  - pip:
    - gym>=0.22.0,<0.23.1
    - yacs>=0.1.8
    - numpy-quaternion>=2019.3.18.14.33.20
    - attrs>=19.1.0
    - opencv-python>=3.3.0
    - pickle5; python_version < '3.8'
