# Parameters of the trapezoidal velocity profile (acceleration & max speed)
#v_max: 0.2  # base.params["motion"]["default"]["vel_m"]
#w_max: 0.45  # (vel_m_max - vel_m_default) / wheel_separation_m
v_max: 0.15  # base.params["motion"]["default"]["vel_m"]
w_max: 0.3  # (vel_m_max - vel_m_default) / wheel_separation_m
acc_lin: 0.2  # 0.5 * base.params["motion"]["max"]["accel_m"]
acc_ang: 0.4  # 0.5 * (accel_m_max - accel_m_default) / wheel_separation_m

# Tolerances for determining whether the goal position or orientation is reached
lin_error_tol: 0.15
ang_error_tol: 0.15

# Error tolerance ratio - scale target error by this to a minimum of the tolerance below
lin_error_ratio: 0.5
ang_error_ratio: 0.5

# Minimum error tolerances we can accept
min_lin_error_tol: 0.04
min_ang_error_tol: 0.05

# Maximum angle error at which the controller would still exert linear motion
max_heading_ang: 0.7854  # 45 degrees

# Maximum distance to goal at which the controller will opt for moving backwards over turning around
max_rev_dist: 0.5

# Time taken before we stop trying
timeout: 10.0
