_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_mae_encoder
  checkpoint_path: /home/cortex/home-robot/projects/imagenav/models/vc1_vitb.pth
  model:
    _target_: eaif_models.models.vit.vit.vit_base_patch16
    img_size: 224
    use_cls: True
    drop_path_rate: 0.0
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_base_patch16
  data:
    - ego
    - imagenet
    - inav
  comment: 182_epochs
