_target_: vc_models.models.load_model
model:
  _target_: vc_models.models.vit.vit.load_mae_encoder
  model:
    _target_: vc_models.models.vit.vit.vit_base_patch16
    use_cls: True
transform:
  _target_: vc_models.transforms.vit_transforms
metadata:
  algo: rand
  model: vit_base
  data: none
